apply plugin: 'com.android.library'

android {
    namespace 'com.swift.sandhook.lib'
    compileSdkVersion 34
    defaultConfig {
        minSdkVersion 21
    }
}

dependencies {
    implementation project(':annotation')

    // 【必须】这一行提供了Kotlin语言的基础支持
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
}